# Generated by Django 3.2.25 on 2024-07-23 00:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nestfinder', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='property',
            options={'permissions': [('can_manage_property', 'Can manage property')]},
        ),
        migrations.AddField(
            model_name='customerprofile',
            name='profile_picture',
            field=models.ImageField(blank=True, null=True, upload_to='customer_profiles/'),
        ),
        migrations.AlterField(
            model_name='property',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=15),
        ),
    ]
