# Generated by Django 3.2.25 on 2024-07-23 07:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nestfinder', '0002_auto_20240722_1708'),
    ]

    operations = [
        migrations.AddField(
            model_name='customerprofile',
            name='phone',
            field=models.CharField(default='0000000000', max_length=15),
        ),
        migrations.AlterField(
            model_name='agentprofile',
            name='phone',
            field=models.CharField(default='0000000000', max_length=15),
        ),
    ]
